//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TurismoReal_Desktop_DALC
{
    using System;
    using System.Collections.Generic;
    
    public partial class ARRIENDO_AMIGO
    {
        public decimal ID { get; set; }
        public decimal ID_ARRIENDO { get; set; }
        public decimal ID_AMIGOS { get; set; }
    
        public virtual AMIGO AMIGO { get; set; }
        public virtual ARRIENDO ARRIENDO { get; set; }
    }
}
