//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TurismoReal_Desktop_DALC
{
    using System;
    using System.Collections.Generic;
    
    public partial class ARRIENDO
    {
        public ARRIENDO()
        {
            this.MULTA = new HashSet<MULTA>();
            this.RESERVA = new HashSet<RESERVA>();
            this.SERVICIO_CONTRATADO = new HashSet<SERVICIO_CONTRATADO>();
            this.SOLICITUD_TRANSPORTE = new HashSet<SOLICITUD_TRANSPORTE>();
            this.AMIGO = new HashSet<AMIGO>();
        }
    
        public decimal ID_ARRIENDO { get; set; }
        public decimal ID_CLIENTE { get; set; }
        public decimal ID_DPTO { get; set; }
        public System.DateTime FECHA_INICIO { get; set; }
        public System.DateTime FECHA_FIN { get; set; }
        public string CHECK_IN { get; set; }
        public string CHECK_OUT { get; set; }
        public decimal TOTAL_ARRIENDO { get; set; }
        public decimal TOTAL_SERVICIOS { get; set; }
    
        public virtual DEPARTAMENTO DEPARTAMENTO { get; set; }
        public virtual USUARIO USUARIO { get; set; }
        public virtual ICollection<MULTA> MULTA { get; set; }
        public virtual ICollection<RESERVA> RESERVA { get; set; }
        public virtual ICollection<SERVICIO_CONTRATADO> SERVICIO_CONTRATADO { get; set; }
        public virtual ICollection<SOLICITUD_TRANSPORTE> SOLICITUD_TRANSPORTE { get; set; }
        public virtual ICollection<AMIGO> AMIGO { get; set; }
    }
}
