//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TurismoReal_Desktop_DALC
{
    using System;
    using System.Collections.Generic;
    
    public partial class CONDUCTOR
    {
        public CONDUCTOR()
        {
            this.TRANSPORTE_REALIZADO = new HashSet<TRANSPORTE_REALIZADO>();
        }
    
        public int ID_CONDUCTOR { get; set; }
        public string NOMBRE { get; set; }
        public string APE_PAT { get; set; }
        public string APE_MAT { get; set; }
        public string TIPO_LICENCIA { get; set; }
        public System.DateTime FEC_NAC { get; set; }
    
        public virtual ICollection<TRANSPORTE_REALIZADO> TRANSPORTE_REALIZADO { get; set; }
    }
}
