//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TurismoReal_Desktop_DALC
{
    using System;
    using System.Collections.Generic;
    
    public partial class DISPONIBILIDAD_SERVICIO
    {
        public decimal ID { get; set; }
        public decimal ID_DPTO { get; set; }
        public decimal ID_SERVICIO { get; set; }
        public string ACTUALMENTE_DISPONIBLE { get; set; }
    
        public virtual DEPARTAMENTO DEPARTAMENTO { get; set; }
        public virtual SERVICIO_EXTRA SERVICIO_EXTRA { get; set; }
    }
}
