//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TurismoReal_Desktop_DALC
{
    using System;
    using System.Collections.Generic;
    
    public partial class ERROR
    {
        public decimal ID_ERROR { get; set; }
        public string ERROR_PROCESO { get; set; }
        public string ERROR_MSG { get; set; }
        public System.DateTime ERROR_FECHA { get; set; }
    }
}
