//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TurismoReal_Desktop_DALC
{
    using System;
    using System.Collections.Generic;
    
    public partial class ERROR
    {
        public decimal ID_ERROR { get; set; }
        public string ERROR_PROCESO { get; set; }
        public string ERROR_MSG { get; set; }
        public System.DateTime ERROR_FECHA { get; set; }
    }
}
