//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TurismoReal_Desktop_DALC
{
    using System;
    using System.Collections.Generic;
    
    public partial class HISTORICO_ARRIENDO
    {
        public decimal ID_ARRIENDO { get; set; }
        public string NOMBRE_CLIENTE { get; set; }
        public string NOMBRE_DPTO { get; set; }
        public System.DateTime FECHA_INICIO { get; set; }
        public System.DateTime FECHA_FIN { get; set; }
        public decimal TOTAL_ARRIENDO { get; set; }
        public decimal TOTAL_MULTAS { get; set; }
        public decimal VALOR_TOURS { get; set; }
        public decimal VALOR_TRANSPORTES { get; set; }
    }
}
