//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TurismoReal_Desktop_DALC
{
    using System;
    using System.Collections.Generic;
    
    public partial class HISTORICO_INGRESO
    {
        public decimal ID_DETALLE { get; set; }
        public decimal ID_DPTO { get; set; }
        public string DEPARTAMENTO { get; set; }
        public System.DateTime FECHA { get; set; }
        public decimal MONTO_ARRIENDO { get; set; }
        public decimal MONTO_MULTAS { get; set; }
    }
}
