//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TurismoReal_Desktop_DALC
{
    using System;
    using System.Collections.Generic;
    
    public partial class HISTORICO_INGRESO
    {
        public decimal ID_DETALLE { get; set; }
        public decimal ID_DPTO { get; set; }
        public string DEPARTAMENTO { get; set; }
        public System.DateTime FECHA { get; set; }
        public decimal MONTO_ARRIENDO { get; set; }
        public decimal MONTO_MULTAS { get; set; }
    }
}
