//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TurismoReal_Desktop_DALC
{
    using System;
    using System.Collections.Generic;
    
    public partial class INVENTARIO
    {
        public decimal ID_INVENTARIO { get; set; }
        public decimal ID_DPTO { get; set; }
        public string NOMBRE { get; set; }
        public decimal VALOR { get; set; }
        public string DISPONIBLE { get; set; }
        public System.DateTime FECHA_COMPRA { get; set; }
    
        public virtual DEPARTAMENTO DEPARTAMENTO { get; set; }
    }
}
