//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TurismoReal_Desktop_DALC
{
    using System;
    using System.Collections.Generic;
    
    public partial class RESERVA
    {
        public decimal ID_RESERVA { get; set; }
        public decimal ID_ARRIENDO { get; set; }
        public string NOM_PERSONA { get; set; }
        public System.DateTime FECHA_RESERVA { get; set; }
        public decimal ACOMPANANTES { get; set; }
        public decimal COSTO_RESERVA { get; set; }
        public string VIGENTE { get; set; }
    
        public virtual ARRIENDO ARRIENDO { get; set; }
    }
}
