//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TurismoReal_Desktop_DALC
{
    using System;
    using System.Collections.Generic;
    
    public partial class RESERVA
    {
        public decimal ID_RESERVA { get; set; }
        public string NOM_PERSONA { get; set; }
        public System.DateTime FECH_ARRIENDO { get; set; }
        public decimal ID_ARRIENDO { get; set; }
        public decimal ACOMPANANTES { get; set; }
        public decimal COSTO_RESERVA { get; set; }
        public string VIGENTE { get; set; }
    }
}
