//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TurismoReal_Desktop_DALC
{
    using System;
    using System.Collections.Generic;
    
    public partial class SERVICIO_CONTRATADO
    {
        public decimal ID { get; set; }
        public decimal ID_ARRIENDO { get; set; }
        public decimal ID_SERVICIO { get; set; }
        public decimal COSTO { get; set; }
        public Nullable<System.DateTime> FECHA_REALIZACION { get; set; }
        public string REALIZADO { get; set; }
    
        public virtual ARRIENDO ARRIENDO { get; set; }
        public virtual SERVICIO_EXTRA SERVICIO_EXTRA { get; set; }
    }
}
