//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TurismoReal_Desktop_DALC
{
    using System;
    using System.Collections.Generic;
    
    public partial class SOLICITUD_TRANSPORTE
    {
        public decimal ID_SOLICITUD { get; set; }
        public decimal ID_ARRIENDO { get; set; }
        public System.DateTime FECHA_INICIO { get; set; }
        public decimal PASAJEROS { get; set; }
        public string DIR_INICIO { get; set; }
        public string DIR_DESTINO { get; set; }
        public string SENTIDO_VIAJE { get; set; }
        public Nullable<decimal> KMS_DISTANCIA { get; set; }
        public string ACEPTADA { get; set; }
        public decimal COSTO { get; set; }
    
        public virtual ARRIENDO ARRIENDO { get; set; }
        public virtual TRANSPORTE_REALIZADO TRANSPORTE_REALIZADO { get; set; }
    }
}
