//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TurismoReal_Desktop_DALC
{
    using System;
    using System.Collections.Generic;
    
    public partial class TRANSPORTE_REALIZADO
    {
        public decimal ID_TRANSPORTE { get; set; }
        public int ID_CONDUCTOR { get; set; }
        public decimal ID_ARRIENDO { get; set; }
        public string DESC_VEHICULO { get; set; }
        public string PATENTE { get; set; }
        public System.DateTime FECHA_INICIO { get; set; }
        public decimal COSTO { get; set; }
    
        public virtual ARRIENDO ARRIENDO { get; set; }
        public virtual CONDUCTOR CONDUCTOR { get; set; }
    }
}
