//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TurismoReal_Desktop_DALC
{
    using System;
    using System.Collections.Generic;
    
    public partial class TRANSPORTE_REALIZADO
    {
        public decimal ID_SOLICITUD { get; set; }
        public int ID_CONDUCTOR { get; set; }
        public string DESC_VEHICULO { get; set; }
        public string PATENTE { get; set; }
    
        public virtual CONDUCTOR CONDUCTOR { get; set; }
        public virtual SOLICITUD_TRANSPORTE SOLICITUD_TRANSPORTE { get; set; }
    }
}
